### ISSUE TITLE
Document the WASM build process for the core

### ISSUE THREAD

**Issue by ianthetechie** [stadiamaps/ferrostar#100]
This task covers the bare minimum to get a wasm module. I think this is pretty straightforward, but we need to decide what looks like the best option + document our choices.

- [x] Do developers doing WASM builds need to have a target installed? If so, consider adding the target tuple to rust-toolchain.toml in the project root.
- [x] Do you need to have any other tools installed?
- [x] Do we use a tool to make it easier? I'd look at [`cargo-wasi`](https://bytecodealliance.github.io/cargo-wasi/index.html); seems to make things easier?
- [ ] Document findings in the guide (mdbook in the repository: https://github.com/stadiamaps/ferrostar/tree/main/guide)

**Comment by ianthetechie** [comment]
I think GitHub's anti-spam is kicking in so I can't assign you yet @CatMe0w, but this is here for your reference. Maybe if you leave a comment on the issue I can assign it?

**Comment by CatMe0w** [comment]
Looks like I can assign myself. But I'll have to check the tasks later.

**Comment by CatMe0w** [comment]
Will we use WASI? Ferrostar Rust core is more like a "pure computation" library in my opinion and doesn't interact with system interfaces by itself. A basic, minimal `wasm32-unknown-unknown` target should be enough.

**Comment by ianthetechie** [comment]
Yes, excellent point :) I think `wasm32-unknown-unknown` is probably enough, and WASI probably isn't needed.

**Comment by ianthetechie** [comment]
Just tried this out myself @CatMe0w and remembered why I suggested WASI ;) We would need to support no-std environments first. See #26 which tracks this. We can compile the core today with WASI though.

**Comment by ianthetechie** [comment]
I've been mulling this over a bit. Might actually need to go ahead and make the core not require WASI as that is _possible_ but not _easy_ to run in a web browser right now. I'll give that a bit of thought. Let me know if you've turned up anything as well @CatMe0w.

**Comment by ianthetechie** [comment]
I think this will be closed by https://github.com/stadiamaps/ferrostar/pull/120. There shouldn't be much else needed to get going this summer; building is a single command, and if you use rustup, it should automatically install the needed toolchains.
