### ISSUE TITLE
Decide on web frontend strategy / frameworks

### ISSUE THREAD

**Issue by ianthetechie** [stadiamaps/ferrostar#109]
I mentioned / we discussed React in the initial conversations and project description, but I want to see if there are any easier paths.

Here are some more options.

[Leptos](https://www.leptos.dev/) might actually very cleanly solve everything from wasm interop with Rust to reactivity. It would be very easy to use with a client side rendering approach but I'm not sure how well it lends itself to packaging the result as a library.

[Seed](https://github.com/seed-rs/seed) - recommended by several at the Seoul Rust meetup. Also unsure how easily one could package libraries with this.

**Comment by ianthetechie** [comment]
Probably also worth noting that we absolutely should have a fairly Vanilla JS core and then **build on top of it** for React (or Vue or Leptos or anything else we target). Frontend frameworks come and go all the time and we should probably look at a few to understand best how to support them all at a foundational level first and then build out for popular ones (like react) over time / in separate repos.

**Comment by CatMe0w** [comment]
Seed is not maintained and that is a big no to me. I also find it has a relatively steep learning curve and for me I would not pick it in the first place. Leptos looks more intuitive and more promising, but I would rather stick with some mature techonologies that are already widely accepted by the industries, such as React and Vue.
