### ISSUE TITLE
Add a FusedLocationProviderClient wrapper

### ISSUE THREAD

**Issue by ianthetechie** [stadiamaps/ferrostar#115]
We want to include a `LocationProvider` backed by `FusedLocationProviderClient`, as this is what most commercial apps will want to use. Some care needs to be taken with this to ensure that it is not an issue for open-source projects wanting to publish on F-Droid, so this will probably end up being an _optional_ separate package. We can still use the same gradle workspace, but it needs to be published separately.

**Comment by Archdoog** [comment]
At a glance, Android doesn't allow fancy conditional package imports. I'd be happy to post my implementation of this as a guide article/code reference. It's not particularly complicated and probably more effective than publishing a separate module that includes for google play?

**Comment by ianthetechie** [comment]
I think a separate module might still be helpful but let's go for the easiest thing for now. You can just throw whatever code / notes you have here in the issue and I can translate it to docs and/or a separate module later.
