### ISSUE TITLE
Create WASM to JS bindings for OsrmResponseParser

### ISSUE THREAD

**Issue by ianthetechie** [stadiamaps/ferrostar#121]
After doing a minimal test of WASM to JS bindings, I'd suggest this is the first "real" project to attempt.

The OSRM parser is just parsing (string) data into our standardized data model. It's also a full "object", so it should be a good representative of future work.

You'll need to ensure all data models (`Route` etc.) are accessible from JavaScript as well. It looks like there are two approaches to this. Some things can be exposed with a `#[wasm_bindgen]` attribute, but others (ex: with collections; probably many of our types) will need to use `serde`. This page documents how to do it in serde: https://rustwasm.github.io/docs/wasm-bindgen/reference/arbitrary-data-with-serde.html. It's nothing out of the ordinary, and we already conditionally derive this anyways for testing on many types.

Completion criteria:

- [ ] Ability to create an instance of `OsrmResponseParser` from JavaScript with configurable polyline precision
- [ ] Ability to parse a string response. It doesn't need to be anything fancy; just a demo JS + HTML where a hard-coded string gets parsed and the result logged to the console or something. Here are [several example strings](https://github.com/stadiamaps/ferrostar/blob/32d8dcd71157d65feb1494e97b2c019d2dbfb2b9/common/ferrostar/src/routing_adapters/osrm/mod.rs#L164)

**Comment by CatMe0w** [comment]
Is this still need to be done now? `OsrmResponseParser` is not exposed via uniffi and `RouteResponseParser` trait is being used instead.  JavaScript implementations intend to follow that as much as possible. (Though, both current Rust core and JS implementations have only OSRM format now.)

**Comment by ianthetechie** [comment]
Good question!

> `OsrmResponseParser` is not exposed via uniffi and `RouteResponseParser` trait is being used instead

Are you referring to this: https://github.com/stadiamaps/ferrostar/blob/27a56410d205ae3136b190f92bef10d1ef075296/common/ferrostar/src/lib.rs#L92?

If so, then the type erasure is intentional (long story; at least in the past, it was not possible to use a non-type-erased version but that may have been fixed; it's not really relevant though). The important thing is that someone could use this to create their own route adapter in Swift or Kotlin for an API that used the OSRM format.

I think we eventually want to do something similar for JavaScript, but I don't think that's super high priority right now. Let's focus first on getting a full + slightly more polished UI first.

If you have any thoughts though on how to expose this using wasm-bindgen, feel free to write them down here or just implement it if it's going to be really quick (less than a day; I would put a time limit on it).

**Comment by CatMe0w** [comment]
It is! It seems that the actual iOS and Android implementations do not use these two functions, making me wonder if they were intended solely for specification purposes. In the early stages of my development, I attempted to export these two functions to JS. However, as I mentioned in our meetings, `Arc` doesn't make sense in JS. Eventually I had to use many wrapper functions to hide all the `Arc`s.

**Comment by ianthetechie** [comment]
Correct; as the iOS and Android repos are primarily libraries with minimal demos, they don't use these directly. They are provided for end users to be able to build their own integrations.

Maybe one bit of missing context is that the industry has largely standardized around the OSRM response format (with proprietary extensions sometimes). So this is a fairly common use case of wanting to integrate with an API that has a custom request format but OSRM responses. It just doesn't show up in the demo apps.
