### ISSUE TITLE
Correct screen rotation and fix recomposition issues

### ISSUE THREAD

**Issue by Archdoog** [stadiamaps/ferrostar#146]
Currently when you rotate the screen, the entire system state resets and navigation starts again. We want to fix this so the user can seamless change their screen orientation whenever in the navigation process to see the view recompose, but not the underlying navigation state.

**Comment by Archdoog** [comment]
This is demo app only (caused the by the LaunchedEffect on the demo navigation scene)

**Comment by ianthetechie** [comment]
@Archdoog I just re-tested this and it looks like it's fixed now. Anything else you're aware of that needs fixing, or should I close this?

**Comment by Archdoog** [comment]
Let's close it. I personally thought it was already resolved and hadn't seen the issue in months.
