### ISSUE TITLE
Camera view moving for web components

### ISSUE THREAD

**Issue by CatMe0w** [stadiamaps/ferrostar#152]
In iOS and Android implementations, there are 3D maps with views that can be rotated to follow the user's direction, but only static 2D maps with a fixed perspective are available in web-based Leaflet. (While it is possible to add third-party plugins to enable rotation, it doesn't make sense for city maps with text.)

Is it necessary to have the view zoom in and follow the user's position automatically?

**Comment by ianthetechie** [comment]
As discussed in #155, we'll be transitioning to MapLibre GL JS, which solves rotation. Though keep in mind that:

1. Compass support in the browser geolocation APIs is not in the best shape yet ([but it's possible maybe??](https://rohit-5oct.medium.com/implement-compass-for-mobile-web-browser-using-javascript-4fd9ab992157))
2. In this case, we will not have background location, making course over ground difficult to track accurately (it could be very noisy).

So, I don't think that heading/course tracking is a requirement for the summer project.

Re: following the user's position automatically, I think that it would be nice to have eventually, but if this takes a lot of time, let's focus on other areas of polish for the summer. I'll try to bring this up in a few weeks again for discussion depending on where we are :)
