### ISSUE TITLE
Use MapLibre GL JS instead of Leaflet

### ISSUE THREAD

**Issue by CatMe0w** [stadiamaps/ferrostar#155]
Leaflet lacks built-in support for rotation and pitch, making it unsuitable for navigation purposes. Additionally, placing a marker that follows the user's orientation is challenging. Although https://github.com/bbecquet/Leaflet.RotatedMarker is mentioned in Leaflet's official documentation, it appears impractical and even ridiculous for navigation:
![image](https://github.com/user-attachments/assets/2f207134-6fc4-4e26-899a-e50bb2384c2b)

Switching to MapLibre GL JS could be a optional long term goal, after stabilizing UI. This would also help reduce the need for workarounds related to Leaflet quirks in modern web toolchains.

**Comment by ianthetechie** [comment]
Closed by #166.
