### ISSUE TITLE
Increase Route Polyline Width

### ISSUE THREAD

**Issue by Archdoog** [stadiamaps/ferrostar#174]
Our current polyline style and width is actually relatively hard to see at screen brightnesses less than maximum out in a car/in the sun. Especially when you're driving and only glancing at the route, it's takes significantly longer to see what's happening than the thicker maplibre/mapbox route poutine.

**Comment by ianthetechie** [comment]
FYI this will probably hit another fundamental limitation of the approach taken by Ramani in relying heavily on the annotations library. See below:

![Image](https://github.com/user-attachments/assets/42e8283c-38af-41a1-993d-782e6bd54ed4)

Meanwhile on iOS, we are able to fully leverage dynamic styling.

![Image](https://github.com/user-attachments/assets/3c80f248-619b-41a4-9482-92be24da6cfa)
