### ISSUE TITLE
Clear notification queue on new route/reroute

### ISSUE THREAD

**Issue by Archdoog** [stadiamaps/ferrostar#179]
We can close this if it's already handled. There were a handful of bugs at play at the same time, so it's entirely likely this was just a symptom of another bug. Anyways, as a placeholder if nothing else.

When a rapid series of re-routes occurs (something we should debounce a bit anyways), the android voice instructions continue to speak the initial instruction from the many re-routes sometimes for many seconds or minutes after the re-route event has succeeded. It seems like each re-route is adding its initial instruction to the queue much faster than the TTS service can recite the content. As a result the queue grows. Eventually it clears though if you remain on course for a while.

This is an android bug, but if it's platform code (kotlin), we should verify/fix iOS as well.

**Comment by ianthetechie** [comment]
I think this is a duplicate of #117.
