### ISSUE TITLE
iOS - Mute Button

### ISSUE THREAD

**Issue by Archdoog** [stadiamaps/ferrostar#194]
Add a mute button to iOS

**Comment by MarekSabol** [comment]
Hi, I would like to take over this issue :)

**Comment by MarekSabol** [comment]
Hi @Archdoog,

 I started working on the implementation and I wanted to know if you have some preference on solution.

I adjusted file DemoNavigationView and created working button to mute and look like the rest of UI:
<img width="256" alt="Snímka obrazovky 2024-10-06 o 14 37 14" src="https://github.com/user-attachments/assets/0c18b691-de7d-4d9e-b0cb-1dc3b626c1d1">

<img width="280" alt="image" src="https://github.com/user-attachments/assets/c1f41797-e9a5-4358-968f-2d81d29f8813">

If you agree with this I would then ask you to assign this issue to me and I will submit this solution.

Thank you so far :)

**Comment by ianthetechie** [comment]
Nice!

I would first look at the Android code as it should be quite similar.

Basically make a SwiftUI mute button view (what you have looks about right!) in the SwiftUI target so it's reusable. Then add it to the default portrait and navigation overlays. I would suggest having it in the same location as Android which I think was upper right. You can se how we do other default views in the flexible grid layout.

Feel free to open up a PR (even a draft) and tag us for a review :)

**Comment by MarekSabol** [comment]
Hi, sorry for late response, but this week was crazy :D, I've created PR IOS Mute button #294.
