### ISSUE TITLE
iOS - missing padding on non-notched (touch id) devices.

### ISSUE THREAD

**Issue by michaelkirk** [stadiamaps/ferrostar#242]
It feels like there should be some manual padding on devices that don't have safe area insets. That includes devices with TouchID like the iPhone SE (3rd generation and prior).

## portrait orientation

<img width="374" alt="Screenshot 2024-09-12 at 16 09 03" src="https://github.com/user-attachments/assets/eb9ddfef-0ae3-415b-8f2e-4783b1f7c396">

- `ArrivalView.bottom`

## landscape orientation

<img width="755" alt="Screenshot 2024-09-12 at 16 08 25" src="https://github.com/user-attachments/assets/6df24a12-e5f8-444d-bff0-f3fb65ec2436">

- `ArrivalView.bottom`
- `ArrivalView.left`
- `Zoom.right`
- `LocateMe.bottom`

Unfortunately, I don't know of a great way to do this. 

Something along the lines of: 
- if safeAreaInsets.bottom are 0, add bottom padding
- if in lanscape orientation, and safeAreaInsets.horizontal are 0, add horizontal padding

Does that seem reasonable?

**Comment by ianthetechie** [comment]
Yeah, that seems reasonable to just fallback to some reasonable values if the `safeAreaInsets` are zero; I want to say `8` or `16` are what the old Human Interface Guidelines recommended... Any opinions / concerns from you @Archdoog?

I have to say I'm slightly surprised by the landscape behavior of the TouchID devices though! I would have expected some horizontal padding (as there appears to be in portrait mode). I guess the `safeAreaInsets` have quite a few quirks. Here's what it looks like on a notched device. I guess they add right padding even though it's not strictly needed? Perhaps for symmetry?

![image](https://github.com/user-attachments/assets/142d6750-650d-4fb7-a9e3-1e0b683a6e61)

**Comment by Archdoog** [comment]
We might just be able to use the default `.padding()` to inset it whenever safe area is zero (believe this is usually 16). But yes, this was quite a complex problem on Android as well w/ Edge to Edge and #213. Basically screens without safe area need additional padding. On more modern screens with safe areas a padding of zero is preferred because there's the additional map padding built in w/ the `safeAreaInsets`.
