### ISSUE TITLE
Android Annotation Flow Publisher

### ISSUE THREAD

**Issue by Archdoog** [stadiamaps/ferrostar#316]
Build the android counterpart to this PR for iOS: https://github.com/stadiamaps/ferrostar/pull/287. 

## In `android/core`

1. An interface that sources the correct flows and provides parity to this swift protocol [AnnotationPublisher.swift#L6](https://github.com/stadiamaps/ferrostar/blob/14b41be53cf5859a3b15c69b61010f760e68078e/apple/Sources/FerrostarCore/Annotations/AnnotationPublisher.swift#L6)
2. A default implementation that uses the a generic type using JSON model and kotlin serialization. See [AnnotationPublisher.swift#L17](https://github.com/stadiamaps/ferrostar/blob/14b41be53cf5859a3b15c69b61010f760e68078e/apple/Sources/FerrostarCore/Annotations/AnnotationPublisher.swift#L17)
3. Install the annotation publishing into ferrostar core and call the configure function.
4. Add the [`MaxSpeed`](https://github.com/stadiamaps/ferrostar/blob/main/apple/Sources/FerrostarCore/Models/MaxSpeed.swift) serializable object. I believe we're using Moshi kotlin for these things, but it looks like we also have Kotlinx.serializable in the plugins. This one is tricky as seen in the swift codable. The model is a janky enum-like multi-format value.
5. Add the [`ValhallaExtendedOSRMAnnotation`](https://github.com/stadiamaps/ferrostar/blob/main/apple/Sources/FerrostarCore/Annotations/Models/ValhallaOSRMAnnotation.swift) model. 
6. Test all the serialization and the publisher.

## In `android/core` bonus (not done in iOS yet).

1. Add functionality to apply or publish annotation data for the entire `Route`. The existing iOS annotation publisher just publishes the current annotations. This would add the ability for the annotation publishing & publisher to add congestion data long the entire route (or route steps).

## In `android/maplibreui`

1. Add the speed limit w/ units & speed limit style to the navigation views and pipe them up to the speed limit (pending #317). This could be deferred to a separate ticket.

**Comment by ahmedre** [comment]
working on this one - have something in progress locally, will push a PR when ready
