### ISSUE TITLE
[iOS] Standard view of upcoming maneuvers

### ISSUE THREAD

**Issue by ianthetechie** [stadiamaps/ferrostar#32]
While not all apps will necessarily _need_ this, I expect that most will want a predesigned view that the user can activate to get a list of the upcoming maneuvers along the route.

**Comment by scenicfinder** [comment]
good idea!

**Comment by Archdoog** [comment]
It would be interesting to brainstorm how we can create a swift protocol and a kotlin interface (or generics) tuned for SwiftUI and Compose and designed to be driven off of the state object for maneuver instructions. Basically focusing on enabling developers to create their concrete implementation that has the basic maneuver instruction state requirements.

That's not necessarily exclusive to a default view. Just thinking how we can make it super easy to build your own UI without loosing functionality provided by the core.

**Comment by ianthetechie** [comment]
Yeah, agreed. It definitely should be something where we enable the developers to easily build their own as well, and I think you're right on focusing on delivering something driven off the state object.

**Comment by michaelkirk** [comment]
I'm interested in working on this for iOS.

Can we talk design first though?

To get the discussion rolling, here's some baselines in other apps:

Here's an example of what this looks like in maplibre:

https://github.com/user-attachments/assets/214d5490-5aec-46d2-b558-c0ad9f191cda

Apple Maps has a very similar UX, though slightly different design treatment.

Google maps does something a bit different - you have to expand the bottom sheet for a list of actions, one of them is "view steps" which pushes a full screen view.

 I was envisioning something along the lines of MapLibre/Apple Maps.

☠️☠️☠️ Forgive the following mockups, they were made with cut and paste. They are intended to be UX oriented, the actual font/color/spacing design would be more reasonable. ☠️☠️☠️

1. Initial state: A handle is visible at the bottom of the InstructionView:

<img src="https://github.com/user-attachments/assets/ae4ad352-86db-465f-b54a-e315743249e5" width=300 />

2. Interactions with the handle, are reminiscent of a sheet UI, so you can tap or drag down on the handle to expose a scrollable list of all the remaining steps:

<img src="https://github.com/user-attachments/assets/e2f17661-e753-44c6-a762-8c8b3b9d0a88" width=300 />


What do you think?

**Comment by ianthetechie** [comment]
That sounds great @michaelkirk!

I think that looking to Apple for design inspiration here is the right call. I really like having an entire "close" button at the bottom one way or another and hiding the arrival info widget. Apple Maps has a better design, but MapLibre Navigation is basically the same concept.

**Comment by Archdoog** [comment]
@michaelkirk Looking like a good start! Some thoughts and notes (happy to discuss them further as nothing is set in stone):

1. I would probably leverage the `DefaultIconographyManeuverInstructionView` and `ManeuverInstructionView` in the same way the `InstructionView` does. There are a few reasons for this:
    - They have the full list of maneuver image icons (ported from Mapbox's Creative Commons svg library). While they're not as fancy as SF Symbols, they're consistent and cover all the configurations. In the future it would be ease to upgrade them if we have a design contribution. 
    - They _should_ automatically handle the icon padding such that all the text should line up vertically with a consistent left padding regardless of text and icon size.
    - They also make use of the theme concept we've used to dynamically color most of the style specific views in both iOS and android.
    - They should be close to flexible enough to handle both the primary instructions view & list of maneuvers.
2. I would probably extend the view to a specific bottom point and a floating footer with a close button. This would be a third way to dismiss (other than tapping the top of the list and swiping up), but would give users less familiar with mobile phone interaction an obvious and consistently placed button to close the list view. Similar to mapbox, but probably styled more like the exit button on our ArrivalView. Though it could easily be full a width pill with text as well. Whether this has like a 16 padding between it and the arrival view or goes full screen I'm not sure.

Feel free to message me on slack if you want to dive into any of the topics. That'd be my rough approach to solving this though 👍

**Comment by michaelkirk** [comment]
Thank you for the helpful context.

My guess is that most people would want this behavior — if there are additional RouteSteps.visualInstructions, you should be able to view them. So my inclination was to include this new UI in the default controls - probably by altering the `InstructionsView`.

To that end, I noticed there is an existing `showPillControl` in the `InstructionsView` which looks exactly like what I was envisioning.

https://github.com/stadiamaps/ferrostar/blob/ae5d8d22ce8d68889444f0c2cd83b37664d69428/apple/Sources/FerrostarSwiftUI/Views/InstructionsView.swift#L71-L72

From what I can tell, it currently has no function. Is there a particular plan for it other than what I'm working on?

**Comment by ianthetechie** [comment]
> if there are additional RouteSteps.visualInstructions, you should be able to view them

I think that's correct.

>  I noticed there is an existing showPillControl in the InstructionsView which looks exactly like what I was envisioning.

Ahh, yes! @Archdoog got very enthusiastic when building the `InstructionsView` and added this since we'd obviously need it later ;) It has no other purpose and is just waiting to be used for this.

**Comment by ianthetechie** [comment]
Nice! This is shaping up really well!
