### ISSUE TITLE
Navigation puck design

### ISSUE THREAD

**Issue by ianthetechie** [stadiamaps/ferrostar#53]

**Comment by Archdoog** [comment]
Here are some Rallista assets we made for the latest mapbox, not sure if maplibre supports glb or they need to be converted. They could use some cleanup and should be changed to a more general purpose blue like the route line.

[Rallista User Puck v2.zip](https://github.com/stadiamaps/ferrostar/files/14412901/Rallista.User.Puck.v2.zip)
[puck_smaller_arrow.glb.zip](https://github.com/stadiamaps/ferrostar/files/14412905/puck_smaller_arrow.glb.zip)

**Comment by ianthetechie** [comment]
I think that _might_ still be usable on Android; we'd need something else for iOS though as glb files are OpenGL-specific.

**Comment by ianthetechie** [comment]
It looks like MapLibre Navigation for iOS [just draws a UIView](https://github.com/maplibre/maplibre-navigation-ios/blob/49b3b701fa8102b77db88aec118f7f56bc59f8fa/MapboxNavigation/UserCourseView.swift#L41) at an appropriate position. I think we briefly discussed that idea a week or two ago.

I assume you have some thoughts on this @Archdoog given that you are using a custom puck.

**Comment by ianthetechie** [comment]
Looks like this might actually not be too bad!

iOS actually gives us a good looking puck for free (unsure when that happened, as MapLibre Navigation still uses a hacked up `UIView` annotation).

Need to confirm how this works on Android, and we'll need to do some work to expose this in Ramani.

Might be relevant: https://github.com/maplibre/maplibre-navigation-android/blob/main/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/map/MapPaddingAdjustor.java

**Comment by ianthetechie** [comment]
Assigning @Archdoog to finish up the basic Android integration (using MapLibre defaults for now); once that's integrated, we can mark this as complete.

**Comment by ianthetechie** [comment]
This is done. We can iterate on this as the remaining issues like puck not showing up correctly z-order-wise are likely a result of the Ramani composables drawing in the wrong order.
