### ISSUE TITLE
Correct VisualInstruction Mismatch Bug

### ISSUE THREAD

**Issue by Archdoog** [stadiamaps/ferrostar#74]
The InstructionsView preview seems to be displaying an incorrect maneuver icon.

**Comment by ianthetechie** [comment]
I just saw this @Archdoog... I think this was fixed in 40bfc81.

<img width="516" alt="image" src="https://github.com/stadiamaps/ferrostar/assets/2140440/ab928fc9-3c30-48fa-8ca2-bd3ab72ca485">
