### ISSUE TITLE
Figure out release automation

### ISSUE THREAD

**Issue by ianthetechie** [stadiamaps/ferrostar#86]
- [ ] Needs to account for 3 platforms (iOS, Android, Rust)
- [ ] iOS just needs a tag adhering to Apple convention
- [ ] Android and Rust are editing a file or two (build.gradle for Android and Cargo.toml for Rust; Rust need to then either run a cargo command or edit the lockfile as well but the latter seems like a bad idea

**Comment by Archdoog** [comment]
Here's a good reference for iOS w/ xcframework. I think we'd just need to conditionally run it on an `release:ios` label or similar. https://github.com/Rallista/valhalla-mobile/blob/main/.github/workflows/ios-release.yml

**Comment by ianthetechie** [comment]
Realized I opened two different issues :P Closing this in favor of #92
