### ISSUE TITLE
ArrivalState from Core for Arrival Views

### ISSUE THREAD

**Issue by Archdoog** [stadiamaps/ferrostar#87]
As discussed on call 4/8. We need an arrival object in the state that defines the estimated time of arrival (ETA) and distance remaining. Some ideas are:

1. Full navigation session - ETA (or duration remaining) and distance remaining
2. Current leg - ETA (or duration remaining) and distance remaining
3. All legs - we could also provide rolling ETA on all legs in the navigation session.

@Archdoog - test what happens w/ multiple legs to inform this issue.

**Comment by ianthetechie** [comment]
Related to #65

**Comment by Archdoog** [comment]
@ianthetechie I believe this should be done with #110 & the `TripProgress` type that's already merged.
