### ISSUE TITLE
ArrivalView for Android

### ISSUE THREAD

**Issue by Archdoog** [stadiamaps/ferrostar#88]
Provide a basic ArrivalView driven off the state for #87 

Feel free to clone this for iOS/Android if we want to split them.

**Comment by ianthetechie** [comment]
Related: #65 ?

**Comment by Archdoog** [comment]
Yeah, we could consolidate these into
- [ ] Create and emit updates for arrival state object on trip state.
- [ ] Create iOS and Android published and arrival view.

**Comment by Archdoog** [comment]
iOS is done. Renamed to android only.

**Comment by ianthetechie** [comment]
Duplicate; closing in favor of #65
