### ISSUE TITLE
Telemetry/CurrentAttributes State from Core

### ISSUE THREAD

**Issue by Archdoog** [stadiamaps/ferrostar#89]
In order to drive various UI features from the state, we need to provide a general purpose state object that can contain values like:

1. The current speed limit at the user's location on the route - if relevant/available `Option<SpeedLimit>`
2. The current filtered speed (e.g. once the core is providing filtered/improved user/vehicle speed) `Option<Speed>`
3. Etc. - Please add other use cases for this.

**Comment by ianthetechie** [comment]
#23 should help as we look toward implementing this.  I think this will give us smoothed/cleaned estimates of position, speed, and course over ground.

**Comment by Archdoog** [comment]
Discussed this with @ianthetechie this week. The idea is to create:

1. A general purpose rust function that get's the index of the next coordinate on the route Pollyanna. This index should match the index in the attributes arrays for the OSRM route type. 
2. A solution to then combine and surface all current values in each attribute array as an "AttributeMap" to platform code. 
3. On the platform level, we can handle the type extraction and usage of values from the map.

Step 2 can be done in a handful ways, e.g. handling basic types in rust, on platform code (swift, kotlin, etc), or even just by passing a json string for platform decoding. Since the data source is expected to be json (ish), where we draw that line depends.

**Comment by ianthetechie** [comment]
Discussed on call: Publishing it as JSON (as bytes/data) and then decoding in platform code. We can provide common models ex: for Valhalla, but this is really easy for anyone to extend using their own model and Codable/Moshi/kotlinx deserialization.
