### ISSUE TITLE
Crashes when clicking on "Start Navigation" on Apple platforms

### ISSUE THREAD

**Issue by CatMe0w** [stadiamaps/ferrostar#91]
This can happen on the Demo App:
`FerrostarCoreFFI/ferrostar.swift:518: Fatal error: 'try!' expression unexpectedly raised an error: FerrostarCoreFFI.(unknown context at $1029b9d94).UniffiInternalError.bufferOverflow`

https://github.com/stadiamaps/ferrostar/blob/6ee817cd3dda844715d305897db1b9c04a7b5127/apple/Sources/UniFFI/ferrostar.swift#L518

**Comment by ianthetechie** [comment]
Hey, good question ;) this actually happens only when there is a mismatch between the Rust code and the Swift bindings. It looks like we are in that state right now as we are between releases. We have release automation planned but until then it's a manual process.

**Comment by CatMe0w** [comment]
After deleting the Xcode and Rust cache many times, I finally found the cause of the problem: After I pulled the latest code,  `useLocalFramework` in Package.swift was reset to false and I didn't notice. That explains why `build-ios.sh` doesn't work in the case and it made me think there was a problem with the code. Sorry for the confusion!
